***
## 3.7 NumPy - Sort, Argsort, Nonzero, and Extract Functions
A variety of sorting related functions are available in NumPy 

***
### Python3.1 Numpy Introduction
### Python3.2 Numpy DataTypes, Functions, and Random Module
### Python3.3 Numpy Iterating Over Arrays
### Python3.4 Numpy Manipulating Arrays
### Python3.5 Numpy Operations
### Python3.6 Numpy File Input and Output and Data Processing
### Python3.7 Numpy-Sort, Argsort, Nonzero, and Extract Functions
### Python3.8 Numpy BreakoutGroupExercises
### Python3.8 Numpy BreakoutGroupExercises - Solutions
***

***
## Table of Contents
### 1. `sort()` Function
### 2. `argsort()` Function
### 3. `nonzero()` Function
### 4. `extract()` Function
***

### 1. `sort()` Function

The sort() function returns a sorted copy of the input array. It has the following parameters:

numpy.sort(a, axis, kind, order)

- a: Array to be sorted

- axis: The axis along which the array is to be sorted. If none, the array is flattened, sorting on the last axis

- kind: Default is quicksort

- order: If the array contains fields, the order of fields to be sorted

In [16]:
import numpy as np  
a = np.array([[3,7,5],[9,1,3]]) 
a

array([[3, 7, 5],
       [9, 1, 3]])

In [17]:
np.sort(a) 

array([[3, 5, 7],
       [1, 3, 9]])

In [18]:
# Sort along axis 0:' 
np.sort(a, axis = 0)

array([[3, 1, 3],
       [9, 7, 5]])

In [19]:
# Sort along axis 1:' 
np.sort(a, axis = 1)

array([[3, 5, 7],
       [1, 3, 9]])

In [20]:
# Order parameter in sort function 
dt = np.dtype([('name', 'S10'),('age', int)]) 
a = np.array([("raju",21),("anil",25),("ravi", 17), ("amar",27)], dtype = dt) 
a

array([(b'raju', 21), (b'anil', 25), (b'ravi', 17), (b'amar', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [21]:
np.sort(a, order = 'name')

array([(b'amar', 27), (b'anil', 25), (b'raju', 21), (b'ravi', 17)],
      dtype=[('name', 'S10'), ('age', '<i4')])

### 2. `argsort()` Function

The numpy argsort() function performs an indirect sort on input array, along the given axis and using a specified kind of sort to return the array of indices of data. This indices array is used to construct the sorted array.

In [22]:
import numpy as np 
x = np.array([3, 1, 2]) 
x

array([3, 1, 2])

In [23]:
y = np.argsort(x)
y

array([1, 2, 0], dtype=int64)

In [24]:
x[y]

array([1, 2, 3])

### 3. `nonzero()` Function

The numpy nonzero() function returns the indices of non-zero elements in the input array.

In [25]:
import numpy as np 

In [26]:
b = np.array([30,40,0]) 
b

array([30, 40,  0])

In [27]:
np.nonzero(b)

(array([0, 1], dtype=int64),)

### 4. `extract()` Function

The numpy extract() function returns the elements satisfying any condition.

In [28]:
import numpy as np 
x = np.arange(9.).reshape(3, 3) 
x

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [29]:
# define a condition 
condition = np.mod(x,2) == 0 
# Element-wise value of condition
condition 

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [30]:
# Extract elements using condition 
np.extract(condition, x)

array([0., 2., 4., 6., 8.])

## Further reading

- http://numpy.scipy.org
- http://scipy.org/Tentative_NumPy_Tutorial
- http://scipy.org/NumPy_for_Matlab_Users - A Numpy guide for MATLAB users.

#### Note: The course materials are developed mainly based on personal experience and contributions from the Python learning community
Referred Books: 
- Learning Python, 5th Edition by Mark Lutz
- Python Data Science Handbook, Jake, VanderPlas
- Python for Data Analysis, Wes McKinney    

Copyright ©2023 Mei Najim. All rights reserved. 